---
kind: pipeline
type: docker
name: build and deploy personal website
trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request
clone:
  disable: true    

steps:

- name: clone
  image: plugins/git
  recursive: true

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.105.0
    validate: false
    url: https://chris.topherward.com
    buildDrafts: false
    buildExpired: false
    buildFuture: false

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 192.168.99.12
    target: /var/www/html/chris
    source: public/*
    rm: false # remove target folder before copy files
    strip_components: 1
    username: root
    password:
      from_secret: ssh_password