baseURL = 'https://chris.topherward.com'
languageCode = 'en-us'
title = 'Christopher Ward'
theme = "ananke"

[markup.goldmark.renderer]
unsafe= true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/yossarianirving"